### ISSUE TITLE
README.md not included in pypi package

### ISSUE THREAD

**Issue by cryptk** [apmorton/pyhidapi#4]
The README.md file is not included in the package that is uploaded to pypi, this results in the following error when trying to `pip install hid`

```
Downloading/unpacking hid (from pyqlight)
  Downloading hid-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-Xro90T/hid/setup.py) egg_info for package hid
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-Xro90T/hid/setup.py", line 5, in <module>
        README = open(os.path.join(here, 'README.md')).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-Xro90T/hid/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-Xro90T/hid/setup.py", line 5, in <module>

    README = open(os.path.join(here, 'README.md')).read()

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-Xro90T/hid/README.md'
```

If you git clone the repository, `python setup.py install` works fine.

The easiest way to fix this would be to just copy README.md to README and then re-package the file as README is included by default in the generated file.

**Comment by cryptk** [comment]
Closing issue in favor of PR #5
